version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: playto_backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*
      # Since Vite runs locally, allow localhost CORS
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173
